### ISSUE TITLE
[Bug] Internal error when adding SET_FAN_SPEED or SET_PIN within on_ready_gcode:

### ISSUE THREAD

**Issue by kostecky** [voidtrance/voron-klipper-extensions#9]
**Describe the bug**
With the new version of klipper installed (this worked in a previous version) certain GCODE causes an internal error when added to the on_ready_gcode: section and klipper is restarted. On bootup, you will get an internal exception.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add `SET_FAN_SPEED FAN=exhaust SPEED=1.0` or whatever fan name you're using to the `on_ready_gcode:` section of the config.
2. Using `SET_PIN PIN=caselight VALUE=1.00` will also cause the same error.
3. Restart klipper.

**Expected behavior**
No exceptions =) - It worked in a prior version.

**Exception trace**
Internal error on command:"SET_FAN_SPEED"
state_notify: 'ready' gcode error: 'EncoderSensor' object has no attribute '_extruder_pos_update_timer'
Traceback (most recent call last):
  File "/home/kris/klipper/klippy/extras/state_notify.py", line 186, in _run_gcode
    res = self.gcode.run_script(script)
  File "/home/kris/klipper/klippy/gcode.py", line 229, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/kris/klipper/klippy/gcode.py", line 211, in _process_commands
    handler(gcmd)
  File "/home/kris/klipper/klippy/gcode.py", line 137, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/kris/klipper/klippy/gcode.py", line 147, in <lambda>
    handler = lambda gcmd: self._cmd_mux(cmd, gcmd)
  File "/home/kris/klipper/klippy/gcode.py", line 315, in _cmd_mux
    values[key_param](gcmd)
  File "/home/kris/klipper/klippy/extras/fan_generic.py", line 25, in cmd_SET_FAN_SPEED
    self.fan.set_speed_from_command(speed)
  File "/home/kris/klipper/klippy/extras/fan.py", line 70, in set_speed_from_command
    toolhead.register_lookahead_callback((lambda pt:
  File "/home/kris/klipper/klippy/toolhead.py", line 576, in register_lookahead_callback
    callback(self.get_last_move_time())
  File "/home/kris/klipper/klippy/toolhead.py", line 360, in get_last_move_time
    self._calc_print_time()
  File "/home/kris/klipper/klippy/toolhead.py", line 315, in _calc_print_time
    self.printer.send_event("toolhead:sync_print_time",
  File "/home/kris/klipper/klippy/klippy.py", line 263, in send_event
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
  File "/home/kris/klipper/klippy/klippy.py", line 263, in <listcomp>
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
  File "/home/kris/klipper/klippy/extras/idle_timeout.py", line 104, in handle_sync_print_time
    self.printer.send_event("idle_timeout:printing",
  File "/home/kris/klipper/klippy/klippy.py", line 263, in send_event
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
  File "/home/kris/klipper/klippy/klippy.py", line 263, in <listcomp>
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
  File "/home/kris/klipper/klippy/extras/filament_motion_sensor.py", line 53, in _handle_printing
    self.reactor.update_timer(self._extruder_pos_update_timer,
AttributeError: 'EncoderSensor' object has no attribute '_extruder_pos_update_timer'
MCU 'rpi' shutdown: Command request

**Repository Verions**
Please, provide the head commit of the following repositories:
- Klipper: v0.12.0-40
- voron-klipper-extensions: 282e1bf522884f2eab912dc559c8f901e4ea642e (HEAD -> master, origin/master, origin/HEAD) [loop_macro] Add support for iteration limits
- Moonraker: 7fc571643d8fd78773a2a02f350db43f5ae934e4 (HEAD -> master) power: enable HTTP port option for Zigbee/Hue devices

**Comment by voidtrance** [comment]
Could you please provide your klippy.log file that includes the crash? I suspect that your fan configuration appears after the `state_notify` configuration and, as a results, the `klippy:ready` handler of the fan gets queued after the `state_notify` handler, which causes the error.

**Comment by voidtrance** [comment]
This has lingered for more than a  month without any response from the original requester. I am closing it.
